config/routes.rb
Rails.application.routes.draw do
  get 'downgrade/new'

  get 'downgrade/create'

  get 'charges/create'

  get 'charges_controller/create'

  devise_for :users

  resources :charges, only: [:new, :create]

  resources :downgrade, only: [:new, :create]

  post 'downgrade/create'

  resources :wikis

  root 'welcome#index'
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :wiki
  belongs_to :user

  def self.update_collaborators(collaborator_string)
    return Collaborator.none if collaborator_string.blank?
    collaborator_string.split(",").map do |collaborator|
      Collaborator.find_or_create_by(email: collaborator.strip)
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :wikis, dependent: :destroy
  has_many :collaborators

  enum role: [:standard, :premium, :admin]

  after_initialize :initialize_role

  def init
     self.role ||= :standard
  end

  def self.going_public(user)
    @wikis = user.wikis.where(private: true)
    @wikis.each do |wiki|
      wiki.update_attribute(private: false)
    end
  end

private

def initialize_role
  self.role ||= :standard
end

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators

  after_initialize :initialize_role

  private

  def initialize_role
    self.private = false if self.private.nil?
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def create
    customer = Stripe::Customer.create(
     email: current_user.email,
     card: params[:stripeToken]
   )

   # Where the real magic happens
   charge = Stripe::Charge.create(
     customer: customer.id, # Note -- this is NOT the user_id in your app
     amount: Amount.default,
     description: "Account Upgrade - #{current_user.email}",
     currency: 'usd'
   )

   current_user.update_attribute(:standard, false)
   current_user.update_attribute(:premium, true)

   flash[:notice] = "Thanks for updating your account, #{current_user.email}! You will now have access to premium content."
   redirect_to root_path

   # Stripe will send back CardErrors, with friendly messages
   # when something goes wrong.
   rescue Stripe::CardError => e
     flash[:alert] = e.message
     redirect_to new_charge_path
  end

  def new
    @stripe_btn_data = {
      key: "#{Rails.configuration.stripe[:publishable_key]}",
      description: "Blocipedia Membership - #{current_user.email}",
      amount: 15_00
    }
  end
  
end

app/controllers/downgrade_controller.rb
class DowngradeController < ApplicationController
  def new
  end

  def create
    current_user.update_attribute(:standard, true)
    current_user.update_attribute(:premium, false)
    current_user.going_public

    flash[:notice] = "You have downgraded your account to standard. We hope to see you back!"

    redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  def index
    @user = current_user
    @wikis = policy_scope(Wiki)
    authorize @wikis
  end

  def show
    @wiki = Wiki.find(params[:id])
    if current_user.present?
      collaborators = []
      @wiki.collaborators.each do |collaborator|
        collaborators << collaborator.email
      end
      unless (@wiki.private == false) || @wiki.user == current_user || collaborators.include?(current_user.email) || current_user.admin?
        flash[:alert] = "You are not authorized to view this wiki"
        redirect_to new_charge_path
      end
    else
      flash[:alert] = "You are not authorized to view this wiki"
      redirect_to new_charge_path
    end
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end

  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def create
    @wiki = Wiki.new(wiki_params)
    @wiki.user = current_user
    authorize @wiki

    if @wiki.save
      @wiki.collaborators = Collaborator.update_collaborators(params[:wiki][:collaborators])
      flash[:notice] = 'You have successfully created a new wiki.'
      redirect_to @wiki
    else
      flash.now[:alert] = 'There was an error while creating your wiki. Please try again.'
      render :new
    end
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.assign_attributes(wiki_params)
    authorize @wiki

    if @wiki.save && (@wiki.user == current_user || current_user == admin?)
      @wiki.collaborators = Collaborator.update_collaborators(params[:wiki][:collaborators])
      flash[:notice] = "Wiki was updated successfully"
      redirect_to @wiki
    elsif @wiki.save
      flash[:notice] = "Wiki was updated successfully"
      redirect_to @wiki
    else
     flash.now[:alert] = 'There was an error updating your wiki. Please try again.'
     render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    @wiki.destroy

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was successfully deleted"
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error while deleting your wiki. Please try again"
      render :show
    end
  end

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action"
    redirect_to(new_user_session_path)
  end

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/downgrade_helper.rb
module DowngradeHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
  def user_is_authorized_to_create?
    current_user && (current_user.admin || current_user.premium?)
  end

  def user_is_authorized_to_update?
    current_user
  end

  def user_is_authorized_to_delete?
    current_user && (current_user == @wiki.user || current_user.admin?)
  end

  def markdown(text)
    extensions = [:tables, :fenced_code_blocks, :autolink, :strikethrough, :underline, :highlight, :quote, :footnotes]
    Markdown.new(text, *extensions).to_html.html_safe
  end
end

app/views/charges/create.html.erb
<h1>Charges#create</h1>
<p>Find me in app/views/charges/create.html.erb</p>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <h4>Click the button!</h4>
  <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
<% end %>

app/views/collaborators/_form.html.erb
<%= f.label :collaborators %>
<%= f.text_field :collaborators,
        class: 'form-control',
        placeholder: "Enter collaborator emails (separated by commas)",
        value: collaborators.map(&:email).join(', ') %> 

app/views/downgrade/create.html.erb
<h1>Downgrade#create</h1>
<p>Find me in app/views/downgrade/create.html.erb</p>

app/views/downgrade/new.html.erb
<h4> Would you like to downgrade your account to standard access?</h4>
<p>Keep in mind that you will have to pay another $15 subscription fee if you wish to upgrade to premium in the future. In addition, all private wikis will become public. </p>
<%= link_to "Downgrade Account", downgrade_create_path, method: :create, class: 'btn btn-danger', data: {confirm: 'Are you sure you wish to downgrade?'} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">

    <ul class="nav nav-tabs">
      <li><%= link_to "Blocipedia", root_path %></li>
      <li><%= link_to "Wikis", wikis_path %></li>

      <div class="nav pull-right user-info">
        <% if user_signed_in? %>
        <div class="pull-right">
           <ul class="nav nav-tabs">
              Signed in as: <strong><%= current_user.email %></strong> |
              
              <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
              <% if current_user.standard? %>
                <li><%= link_to "Upgrade to Premium", new_charge_path, :class => 'navbar-link' %></li>
              <% elsif current_user.premium? %>
                <li><%= link_to "Downgrade Account", new_downgrade_path, :class => 'navbar-link' %></li>
              <% end %>

              <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
            <% else %>
              <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %>
              <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link' %>
            <% end %>
          </ul>
        </div>

      </div>
    </ul>

    </br>

    <% if flash[:notice] %>
      <div class="alert alert success">
        <button type="button" class="close" data-dismiss="alert">&times:</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
      </div>

    <% end %>

</div>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1 class="text-center">Blocipedia: Social, Markdown Wikis</h1>

<br/>
  <div class="jumbotron text-center pagination-centered">
    <h3>Create and share Markdown Wikis</h3>
    </br>
    <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-success text-center' %>
  </div>
</br>

app/views/wikis/create.html.erb
<h1>Wikis#create</h1>
<p>Find me in app/views/wikis/create.html.erb</p>

app/views/wikis/destroy.html.erb
<h1>Wikis#destroy</h1>
<p>Find me in app/views/wikis/destroy.html.erb</p>

app/views/wikis/edit.html.erb
<% if user_is_authorized_to_update? %>
    <h1>Edit Wiki</h1>

    <div class="row">
        <div class="col-md-4">
            <p>Wiki rules</p>
            <ul>
                <li>Write Useful Content</li>
                <li>Please Don't Post Duplicate Content</li>
            </ul>
        </div>
        <div class="col-md-8">
            <%= form_for @wiki do |f| %>
                <div class="form-group">
                    <%= f.label :title %>
                    <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
                </div>
                <div class="form-group">
                    <%= f.label :body %>
                    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
                </div>

                <% if user_is_authorized_to_create? %>
                    <div class="form-group">
                        <%= f.label :private, class: 'checkbox' do %>
                            <%= f.check_box :private %> Private wiki
                        <% end %>
                    </div>
                    <div class="form-group">
                      <%= render partial: 'collaborators/form', locals: { f: f, collaborators: @wiki.collaborators } %>
                    </div>
                <% end %>
                <div class="form-group">
                    <%= f.submit "Save", class: 'btn btn-success' %>
                </div>
            <% end %>
        </div>
    </div>
<% end %>

app/views/wikis/index.html.erb
<h1>My Wikis</h1>

<% @wikis.each do |wiki| %>
  <div class="Well">
    <h3><%= wiki.title %></h3>
    <%= link_to "Keep Reading", wiki.title, wiki, class: 'btn btn-default' %>
    <% end %>
  </div>

  <div class="col-md-4">
    <%= link_to "New Public Wiki", new_wiki_path, class: 'btn btn-success' %>
  </div>

</div>

app/views/wikis/new.html.erb
<% if user_is_authorized_to_create? %>
    <h1>New Wiki</h1>
    <div class="row">
        <div class="col-md-4">
            <p>Wiki rules</p>
            <ul>
                <li>Please Post Useful Content</li>
                <li>Please Don't Post Duplicate Content</li>
            </ul>
        </div>
        <div class="col-md-8">
            <%= form_for @wiki do |f| %>
                <div class="form-group">
                    <%= f.label :title %>
                    <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
                </div>
                <div class="form-group">
                    <%= f.label :body %>
                    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
                </div>
                <div class="form-group">
                    <%= f.label :private, class: 'checkbox' do %>
                        <%= f.check_box :private %> Private wiki
                    <% end %>
                </div>
                <div class="form-group">
                  <%= render partial: 'collaborators/form', locals: { f: f, collaborators: @wiki.collaborators } %>
                </div>
                <div class="form-group">
                        <%= f.submit "Save", class: 'btn btn-success' %>
                </div>
            <% end %>
        </div>
    </div>
<% end %>

app/views/wikis/show.html.erb
<div>
  <h1>
    <%= @wiki.title %> <br>
  </h1>
  <small>
    submitted <%= time_ago_in_words(@wiki.created_at) %> ago
  </small>
</div>

<div class="row">
  <div class="col-md-8">
    <p><%= markdown(@wiki.body) %></p>
    <p>Created by <%= wiki.user.email %></p>
    <p> Collaborators:
      <% unless @wiki.collaborators.empty? %>
        <% @wiki.collaborators.each do |collaborator| %>
          <p><%= collaborator.email %></p>
        <% end %>
      <% end %></p>
  </div>
  <div class="col-md-4">
    <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
    <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-success', data: {confirm: 'Are you sure you wish to delete this wiki?'} %>
  </div>
</div>

app/views/wikis/update.html.erb
<h1>Wikis#update</h1>
<p>Find me in app/views/wikis/update.html.erb</p>